services:
  postgres:
    image: postgres:15
    container_name: sortwater_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sortwater
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: sortwater_redis
    ports:
      - "127.0.0.1:6379:6379"

  react_app:
    build:
      context: ./react_app
      dockerfile: Dockerfile
    container_name: sortwater_react_app
    environment:
      - PGHOST=postgres
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - PGDATABASE=sortwater
      - REDIS_URL=redis://redis:6379
      - NODE_ENV=production
    depends_on:
      - postgres
      - redis
    ports:
      - "127.0.0.1:5050:5050"
    volumes:
      - ./react_app/backend/public:/public

  bot:
    build:
      context: .                           # весь репозиторий
      dockerfile: sortwaterai-bot/Dockerfile
    container_name: sortwater_bot
    env_file:
      - ./sortwaterai-bot/.env
    depends_on:
      - react_app
      - redis
      - postgres
    volumes:
      - ./sortwaterai-bot:/app            # код бота
      - ./ai_functions:/app/ai_functions  # скрипты и модели AI

volumes:
  postgres_data:
