version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: sortwater_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sortwater
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: sortwater_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
